name: Daily Weather Presence

on:
  push:                # lets you test it immediately on push
    branches: [ main ]
  workflow_dispatch:   # adds the “Run workflow” button
  schedule:
    - cron: '30 12 * * *'   # 05:30 AM PT (12:30 UTC)

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run smoke test
        env:
          WEATHER_URL: 'https://www.weather.gov/'
          TITLE_KEYWORD: 'Weather'
        run: pytest -q
